services:
  - type: web
    name: quiz-game
    runtime: python
    buildCommand: pip install -r requirements.txt && python3 migrate_add_is_public.py
    startCommand: gunicorn -c gunicorn_config.py wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
